# Generated by Django 4.2.4 on 2023-09-26 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_author_post_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 15, 59, 0, 157689, tzinfo=datetime.timezone.utc)),
        ),
    ]
